name: envoy
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.9
  http: ^0.13.3
  image: ^3.0.2
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: envoyRegular
      fonts:
        - asset: assets/fonts/envoyRegular.ttf

    - family: montserratRegular
      fonts:
        - asset: assets/fonts/montserratRegular.ttf
